// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "ctre/Phoenix.h"
#include "ConveyorBelts.h"
#include "LiveWindow/LiveWindow.h"
#include "PIDController.h"
#include "PIDSource.h"
#include "PIDOutput.h"
#include "../Robot.h"
#include "../OI.h"
#include "Robot.cpp"
#include "OI.cpp"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

ConveyorBelts::ConveyorBelts() : frc::Subsystem("ConveyorBelts") {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    leftConveyorBelt = RobotMap::conveyorBeltsleftConveyorBelt;
    rightConveyorBelt = RobotMap::conveyorBeltsrightConveyorBelt;
    conveyorDrive = RobotMap::conveyorBeltsConveyorDrive;
    limitSwitch1 = RobotMap::conveyorBeltsLimitSwitch1;
    limitSwitch2 = RobotMap::conveyorBeltsLimitSwitch2;
    talonSRX1 = RobotMap::conveyorBeltsTalonSRX1;
    talonSRX2 = RobotMap::conveyorBeltsTalonSRX2;

    conveyorLeft = Robot::oi->getJoystick1();
    conveyorRight = Robot::oi->getclimber();
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    /*`
     * for the controlling of the belt, there will be two joysticks,
     * controls will be similar to driving except with two conveyor belts
     */
}

void ConveyorBelts::InitDefaultCommand() {
    // Set the default command for a subsystem here.
    // SetDefaultCommand(new MySpecialCommand());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}

void ConveyorBelts::Periodic() {
    // Put code here to be run every loop
	double leftSpeed = conveyorLeft->GetY();
	double rightSpeed = conveyorRight->GetY();
	leftConveyorBelt->Set(leftSpeed);
	rightConveyorBelt->Set(rightSpeed);
}


// Put methods for controlling this subsystem
// here. Call these from Commands.

