// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#ifndef CONVEYORBELTS_H
#define CONVEYORBELTS_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
#include "Robot.h"
#include "OI.h"

class ConveyorBelts: public frc::Subsystem {
private:
	// It's desirable that everything possible is private except
	// for methods that implement subsystem capabilities
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	std::shared_ptr<WPI_TalonSRX> leftConveyorBelt;
	std::shared_ptr<WPI_TalonSRX> rightConveyorBelt;
	std::shared_ptr<frc::DifferentialDrive> conveyorDrive;
	std::shared_ptr<frc::DigitalInput> limitSwitch1;
	std::shared_ptr<frc::DigitalInput> limitSwitch2;
	std::shared_ptr<WPI_TalonSRX> talonSRX1;
	std::shared_ptr<WPI_TalonSRX> talonSRX2;

	Robot robot;
	std::shared_ptr<frc::Joystick> rightconveyorJoystick;
	std::shared_ptr<frc::Joystick> leftconveyorJoystick;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
public:
	ConveyorBelts();
	void InitDefaultCommand() override;
	void Periodic() override;
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
};

#endif
