// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef MOBILITY_H
#define MOBILITY_H

#include "Commands/PIDSubsystem.h"
#include "WPILib.h"
#include <ctre/Phoenix.h>
#include "Robot.h"
#include "Robot.cpp"

class Mobility: public frc::PIDSubsystem {
 public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	std::shared_ptr<frc::SpeedController> fLspeedController;		//fL = front left
	std::shared_ptr<frc::SpeedController> rLspeedController;		//rL = right left
	std::shared_ptr<frc::SpeedController> fRspeedController;
	std::shared_ptr<frc::SpeedController> rRspeedController;

	std::shared_ptr<WPI_TalonSRX> frontLeftMotor;
	std::shared_ptr<WPI_TalonSRX> rearLeftMotor;
	std::shared_ptr<WPI_TalonSRX> frontRightMotor;
	std::shared_ptr<WPI_TalonSRX> rearRightMotor;

	std::shared_ptr<frc::SpeedControllerGroup> leftSpeedController;
	std::shared_ptr<frc::SpeedControllerGroup> rightSpeedController;

	std::shared_ptr<frc::DifferentialDrive> differentialDrive1;

	std::shared_ptr<frc::Encoder> leftEncoder;
	std::shared_ptr<frc::Encoder> rightEncoder;

	Robot robot;
	std::shared_ptr<frc::Joystick> leftJoystick;
	std::shared_ptr<frc::Joystick> rightJoystick;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	Mobility();
	double ReturnPIDInput() override;
	void UsePIDOutput(double output) override;
	void InitDefaultCommand() override;
	void move();
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
};

#endif
